"""Add multi-tenancy business_id

Revision ID: 18006a30996f
Revises: f52fd5d1ffbb
Create Date: 2026-08-07 17:04:13.285023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18006a30996f'
down_revision: Union[str, None] = 'f52fd5d1ffbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.add_column('alerts', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'alerts', 'businesses', ['business_id'], ['id'])
    op.add_column('categories', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'businesses', ['business_id'], ['id'])
    op.add_column('customers', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['id'])
    op.add_column('forecasts', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'forecasts', 'businesses', ['business_id'], ['id'])
    op.add_column('products', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'businesses', ['business_id'], ['id'])
    op.add_column('sales', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'businesses', ['business_id'], ['id'])
    op.add_column('suppliers', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'suppliers', 'businesses', ['business_id'], ['id'])
    op.add_column('uploaded_datasets', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'uploaded_datasets', 'businesses', ['business_id'], ['id'])
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'business_id')
    op.drop_constraint(None, 'uploaded_datasets', type_='foreignkey')
    op.drop_column('uploaded_datasets', 'business_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'business_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'business_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'business_id')
    op.drop_constraint(None, 'forecasts', type_='foreignkey')
    op.drop_column('forecasts', 'business_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'business_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'business_id')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'business_id')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
