"""Add reset_otp columns

Revision ID: ba757f8ac6d8
Revises: 18006a30996f
Create Date: 2026-08-09 17:54:26.094075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba757f8ac6d8'
down_revision: Union[str, None] = '18006a30996f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_alerts_id'), 'anomaly_alerts', ['id'], unique=False)
    op.add_column('users', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expiry')
    op.drop_column('users', 'reset_otp')
    op.drop_index(op.f('ix_anomaly_alerts_id'), table_name='anomaly_alerts')
    op.drop_table('anomaly_alerts')
    # ### end Alembic commands ###
