"""Add user preferences (bio, currency, timezone)

Revision ID: e2d4f8a1c3b5
Revises: c4a19f2b7d1e
Create Date: 2026-08-12 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d4f8a1c3b5'
down_revision: Union[str, None] = 'c4a19f2b7d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('preferred_currency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_currency')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
