"""use full_name for customer

Revision ID: f51659f40fdc
Revises: 31e4d514e2b8
Create Date: 2026-08-07 14:56:03.800070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51659f40fdc'
down_revision: Union[str, None] = '31e4d514e2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('full_name', sa.String(), nullable=True))
    op.execute("UPDATE customers SET full_name = first_name || ' ' || last_name")
    op.alter_column('customers', 'full_name', nullable=False)
    op.drop_column('customers', 'first_name')
    op.drop_column('customers', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('customers', 'full_name')
    # ### end Alembic commands ###
